databases:
  - name: [tabiran-postgresql]
    databaseName: [tabiran_db]
    user: [ken]
    region: Oregon

services:
  - type: web
    name: [tabiran-postgresql]
    env: ruby
    region: Oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    preDeployCommand: ./bin/rails db:migrate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: [tabiran-postgresql]
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2